services:
  - type: web
    name: inspection-report-api
    runtime: python
    rootDir: backend
    buildCommand: git lfs install && git lfs pull && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.11"
